import "package:flutter/material.dart";

ColorScheme lightScheme() {
  return const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff1b62cd),
    surfaceTint: Color(0xff415e91),
    onPrimary: Color(0xffffffff),
    primaryContainer: Color(0xffd7e3ff),
    onPrimaryContainer: Color(0xff284777),
    secondary: Color(0xffcf7516),
    onSecondary: Color(0xffffffff),
    secondaryContainer: Color(0xffffdcc0),
    onSecondaryContainer: Color(0xff6a3b02),
    tertiary: Color(0xff705574),
    onTertiary: Color(0xffffffff),
    tertiaryContainer: Color(0xfffad8fd),
    onTertiaryContainer: Color(0xff573e5c),
    error: Color(0xffba1a1a),
    onError: Color(0xffffffff),
    errorContainer: Color(0xffffdad6),
    onErrorContainer: Color(0xff93000a),
    surface: Color(0xfff9f9ff),
    onSurface: Color(0xff191c20),
    onSurfaceVariant: Color(0xff44474e),
    outline: Color(0xff74777f),
    outlineVariant: Color(0xffc4c6d0),
    shadow: Color(0xff000000),
    scrim: Color(0xff000000),
    inverseSurface: Color(0xff2e3036),
    inversePrimary: Color(0xffaac7ff),
    primaryFixed: Color(0xffd7e3ff),
    onPrimaryFixed: Color(0xff001b3e),
    primaryFixedDim: Color(0xffaac7ff),
    onPrimaryFixedVariant: Color(0xff284777),
    secondaryFixed: Color(0xffffdcc0),
    onSecondaryFixed: Color(0xff2d1600),
    secondaryFixedDim: Color(0xfffeb877),
    onSecondaryFixedVariant: Color(0xff6a3b02),
    tertiaryFixed: Color(0xfffad8fd),
    onTertiaryFixed: Color(0xff28132e),
    tertiaryFixedDim: Color(0xffddbce0),
    onTertiaryFixedVariant: Color(0xff573e5c),
    surfaceDim: Color(0xffd9d9e0),
    surfaceBright: Color(0xfff9f9ff),
    surfaceContainerLowest: Color(0xffffffff),
    surfaceContainerLow: Color(0xfff3f3fa),
    surfaceContainer: Color(0xffededf4),
    surfaceContainerHigh: Color(0xffe7e8ee),
    surfaceContainerHighest: Color(0xffe2e2e9),
  );
}
