// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVlcGWMM-O4-mQ0QzoghQZb5jdBGTFesE',
    appId: '1:1059735946958:android:810b6e5e260b0c92d8329f',
    messagingSenderId: '1059735946958',
    projectId: 'smart-learning-2c505',
    databaseURL: 'https://smart-learning-2c505.firebaseio.com',
    storageBucket: 'smart-learning-2c505.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF5SjhjUxbT0j2lFvN9z_mSwVtr2YpVn4',
    appId: '1:1059735946958:ios:5f5c5055347276fad8329f',
    messagingSenderId: '1059735946958',
    projectId: 'smart-learning-2c505',
    databaseURL: 'https://smart-learning-2c505.firebaseio.com',
    storageBucket: 'smart-learning-2c505.appspot.com',
    androidClientId: '1059735946958-1sssmhqh0fh3jt9orkjpks1hstcuj8b2.apps.googleusercontent.com',
    iosBundleId: 'com.mahmoudhamdyae.social',
  );

}